SELECT * FROM RESERVATION;
DELETE FROM RESERVATION WHERE RESERVECODE>81;

-- #. 예약 가능 방 조회 쿼리
SELECT * FROM ROOM WHERE ROOMCODE NOT IN (SELECT ROOMCODE FROM RESERVATION  -- 예약이 있는 방번호를 제외한 애들을 출력하겠다.
-- 예약이 있는 애들이 어떤 애들이냐면
WHERE HOTELCODE='AAA' -- AAA호텔의 예약들중에 
-- AND RESERVECHECKIN >= SYSDATE -- 오늘 이후의9 예약들중에 // 이렇게 넣으니까 숙박중인 객실이 걸러지잖아 멍청아 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 그렇다고 다 뒤져보기도 뭐한데......
AND (RESERVECHECKIN BETWEEN '2019-04-24' AND TO_DATE('2019-04-25','YYYY-MM-DD')-1  -- 체크인날짜가 내가 선택한 기간에 걸치거나
OR RESERVECHECKOUT BETWEEN TO_DATE('2019-04-24','YYYY-MM-DD')+1 AND '2019-04-25'  -- 체크아웃날짜가 내가 선택한 기간에 걸치거나
OR ('2019-04-24' >= RESERVECHECKIN AND '2019-04-25' <= RESERVECHECKOUT) -- 내가 선택한 기간이 기존 예약기간에 포함되거나
OR ('2019-04-24' <= RESERVECHECKIN AND '2019-04-25' >= RESERVECHECKOUT))) -- 내가 선택한 기간이 기존 예약기간을 포함하거나
AND ROOMGRADE='STANDARD' -- 근데 그중에 스위트룸만
AND ROOMLIMIT>=2 -- 인원수도 체크하고
ORDER BY ROOMCODE; -- 방이름순으로 정렬

        SELECT * FROM ROOM WHERE ROOMCODE NOT IN (SELECT ROOMCODE FROM RESERVATION
		WHERE HOTELCODE='AAA'
        AND (RESERVECHECKIN BETWEEN '2019-04-12' AND TO_DATE('2019-04-14','YYYY-MM-DD')-1
		OR RESERVECHECKOUT BETWEEN TO_DATE('2019-04-12','YYYY-MM-DD')+1 AND '2019-04-14'
		OR ('2019-04-12' >= RESERVECHECKIN AND '2019-04-14' <= RESERVECHECKOUT)
		OR ('2019-04-12' <= RESERVECHECKIN AND '2019-04-14' >= RESERVECHECKOUT)))
		AND ROOMGRADE='STANDARD'
		AND ROOMLIMIT>=2
		ORDER BY ROOMCODE;
        
        SELECT * FROM ROOM WHERE ROOMCODE NOT IN (SELECT ROOMCODE FROM RESERVATION 
        WHERE HOTELCODE='AAA' 
        AND (RESERVECHECKIN BETWEEN '2019-04-19' AND TO_DATE('2019-04-22','YYYY-MM-DD')-1 
        OR RESERVECHECKOUT BETWEEN TO_DATE('2019-04-19','YYYY-MM-DD')+1 AND '2019-04-22' 
        OR ('2019-04-19' >= RESERVECHECKIN AND '2019-04-22' <= RESERVECHECKOUT) 
        OR ('2019-04-19' <= RESERVECHECKIN AND '2019-04-22' >= RESERVECHECKOUT))) 
        --AND ROOMGRADE='SUITE' 
        AND ROOMLIMIT>=2 
        ORDER BY ROOMCODE;
        
        SELECT * FROM ROOM WHERE ROOMCODE NOT IN (SELECT ROOMCODE FROM RESERVATION 
        WHERE HOTELCODE='AAA' 
        AND (RESERVECHECKIN BETWEEN '2019-04-19' AND TO_DATE('2019-04-22','YYYY-MM-DD')-1 
        OR RESERVECHECKOUT BETWEEN TO_DATE('2019-04-19','YYYY-MM-DD')+1 AND '2019-04-22' 
        OR ('2019-04-19' >= RESERVECHECKIN AND '2019-04-22' <= RESERVECHECKOUT) 
        OR ('2019-04-19' <= RESERVECHECKIN AND '2019-04-22' >= RESERVECHECKOUT))) 
        AND ROOMLIMIT>=2 
        ORDER BY ROOMCODE;
        
        SELECT * FROM ROOM WHERE ROOMCODE NOT IN (SELECT ROOMCODE FROM RESERVATION
		WHERE HOTELCODE='AAA' 
         AND (RESERVECHECKIN BETWEEN '2019-04-19' AND TO_DATE('2019-04-22','YYYY-MM-DD')-1 ))
		
		ORDER BY ROOMCODE;
commit;
SELECT 'true' FROM DUAL WHERE (SELECT RESERVECHECKIN FROM RESERVATION WHERE RESERVECODE=7922) BETWEEN '2019-04-21' AND '2019-04-22';
SELECT 'true' FROM DUAL WHERE (SELECT RESERVECHECKOUT FROM RESERVATION WHERE RESERVECODE=7922) BETWEEN '2019-04-22' AND '2019-04-23';
SELECT 'true' FROM DUAL WHERE '2019-04-21' >= (SELECT RESERVECHECKIN FROM RESERVATION WHERE RESERVECODE=7922) AND '2019-04-23' <= (SELECT RESERVECHECKOUT FROM RESERVATION WHERE RESERVECODE=7922);
SELECT 'true' FROM DUAL WHERE '2019-04-21' <= (SELECT RESERVECHECKIN FROM RESERVATION WHERE RESERVECODE=7922) AND '2019-04-23' >= (SELECT RESERVECHECKOUT FROM RESERVATION WHERE RESERVECODE=7922);


 
-- CF) 무조건 예약의 앞에있거나 무조건 예약의 뒤에 있을것
SELECT * FROM RESERVATION 
WHERE RESERVECHECKIN >= SYSDATE 
AND ('2019-04-24' < RESERVECHECKIN AND '2019-04-25' <= RESERVECHECKIN)
OR ('2019-04-24' >= RESERVECHECKOUT AND '2019-04-25' > RESERVECHECKOUT);
-- 근데 이러면 예약이 아예 없는 방이 안나오넼ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 젠장

-- #.예약 쿼리
INSERT INTO RESERVATION (RESERVECODE, HOTELCODE, ROOMCODE, GUESTID, RESERVECHECKIN, RESERVECHECKOUT, PAIDPRICE) VALUES (RESERVATION_SEQ.NEXTVAL, 'AAA', 'ROOM4', 'ggg', '2019-04-26', '2019-04-30', 170000);

-- #. 예약 하나 가져오기
SELECT RESERVE.*, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM 
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE) 
AND RESERVECODE='7922';

-- #. 내가 방금 한 예약번호 가져오기
SELECT MAX(RESERVECODE) FROM RESERVATION RESERVE, HOTEL, ROOM 
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE) 
AND GUESTID='ggg' ;

-- #> 나의 지난 예약 조회(사용자) : 검색조건 - 호텔별, 객실별, 기간별
SELECT RESERVE.*, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM 
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE) 
AND GUESTID='ggg' 
AND RESERVECHECKOUT<EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
--AND RESERVE.HOTELCODE='AAA' -- 호텔별
AND HOTELNAME LIKE '%'||'TEL'||'%'
AND ROOMGRADE='STANDARD' -- 객실별
AND (RESERVECHECKIN>='2019-02-10' AND RESERVECHECKIN<='2019-04-10') -- 기간별(지난 6개월, 3개월일 경우 3/10 부분은 SYSDATE처리)
ORDER BY RESERVECHECKIN DESC; -- 최근예약순으로 정렬

-- -- TOP-N
SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM (
SELECT RESERVE.*, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM 
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE) 
AND GUESTID='ggg' 
AND RESERVECHECKOUT<EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
AND RESERVE.HOTELCODE='AAA'
AND ROOMGRADE='STANDARD'
AND (RESERVECHECKIN>='2019-02-10' AND RESERVECHECKIN<='2019-04-30') 
ORDER BY RESERVECHECKIN DESC
) ALLIAS) WHERE RN BETWEEN 2 AND 4;

-- #. 나의 앞으로 예약 조회(사용자) : 검색조건 - 호텔별
SELECT RESERVE.*, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM 
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE) 
AND GUESTID='ggg' 
AND RESERVECHECKIN>=EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
AND RESERVE.HOTELCODE='AAA' -- 호텔별
ORDER BY RESERVECHECKIN ASC; -- 먼저 도래할 예약순으로 정렬

-- -- TOP-N
SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM (
SELECT RESERVE.*, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM 
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE) 
AND GUESTID='ggg' 
AND RESERVECHECKIN>=EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
AND RESERVE.HOTELCODE='AAA'
ORDER BY RESERVECHECKIN ASC
) ALLIAS) WHERE RN BETWEEN 2 AND 4;

-- #. 현재 예약 현황(관리자용) : 검색조건 - 객실별, 날짜별(입실일기준 하루단위), 고객별
SELECT RESERVE.*, GUESTNAME, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM, GUEST
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE AND RESERVE.GUESTID=GUEST.GUESTID) 
AND RESERVE.HOTELCODE='AAA' 
AND RESERVECHECKIN>=EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE) -- SYSDATE로 하면 당일예약이 잘리네 돌겠네 ㅋㅋㅋㅋㅋㅋㅋㅋ 

ORDER BY RESERVECHECKIN ASC; 

-- -- TOP-N
SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM (
SELECT RESERVE.*, GUESTNAME, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM, GUEST
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE AND RESERVE.GUESTID=GUEST.GUESTID) 
AND RESERVE.HOTELCODE='AAA' 
AND RESERVECHECKIN>=EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
AND ROOMGRADE='STANDARD' 
AND RESERVECHECKIN='2019-04-11'
AND GUESTNAME LIKE '%'||'guest01'||'%'
ORDER BY RESERVECHECKIN ASC
) ALLIAS) WHERE RN BETWEEN 2 AND 4;

-- #. 지난 예약 조회(관리자용) : 검색조건 - 기간별, 고객별, 객실별
SELECT RESERVE.*, GUESTNAME, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM, GUEST
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE AND RESERVE.GUESTID=GUEST.GUESTID) 
AND RESERVE.HOTELCODE='AAA'
AND RESERVECHECKOUT<EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
AND (RESERVECHECKIN>='2019-02-10' AND RESERVECHECKIN<='2019-04-10') -- 기간별
AND GUESTNAME LIKE '%'||'guest01'||'%' -- 고객별
AND ROOMGRADE='STANDARD' -- 객실별
ORDER BY RESERVECHECKIN DESC;


-- -- TOP-N
SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM (
SELECT RESERVE.*, GUESTNAME, HOTELNAME, ROOMNAME, ROOMGRADE, ROOMCOST FROM RESERVATION RESERVE, HOTEL, ROOM, GUEST
WHERE (RESERVE.HOTELCODE=HOTEL.HOTELCODE AND RESERVE.ROOMCODE=ROOM.ROOMCODE AND RESERVE.GUESTID=GUEST.GUESTID) 
AND RESERVE.HOTELCODE='AAA'
AND RESERVECHECKOUT<EXTRACT(YEAR FROM SYSDATE)||'-'||EXTRACT(MONTH FROM SYSDATE)||'-'||EXTRACT(DAY FROM SYSDATE)
AND (RESERVECHECKIN>='2019-02-10' AND RESERVECHECKIN<='2019-04-10') 
AND GUESTNAME LIKE '%'||'guest01'||'%' 
AND ROOMGRADE='STANDARD' 
ORDER BY RESERVECHECKIN DESC
) ALLIAS) WHERE RN BETWEEN 2 AND 4;

-- #. 예약 취소 (5일전 70%/ 3일전 50%/ 1일전 20%/ 당일취소불가)
DELETE FROM RESERVATION WHERE RESERVECODE='0000';

-- -- 포인트 복귀 쿼리
UPDATE GUEST SET GUESTPOINT=GUESTPOINT+500 WHERE GUESTID='ggg';

-- #. 리뷰 작성시 예약의 리뷰 작성 여부 업데이트
UPDATE RESERVATION SET REVIEWSTATUS=1 WHERE RESERVECODE=90;

-- -- ★ TOP-N 구문 틀 : SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM () ALLIAS) WHERE RN BETWEEN 2 AND 4;


-- TEST AREA
SELECT 'TRUE' FROM DUAL WHERE 9 BETWEEN 5 AND 9; -- BETWEEN은 이상(>=)+이하(<=)의 개념(기준 숫자와 같은 경우도 포함한다)

SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
SELECT TO_CHAR(RESERVECHECKIN, 'YYYY-MM-DD HH24:MI:SS') FROM RESERVATION;
SELECT TO_CHAR(SYSDATE-(1/24),'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;
SELECT TO_CHAR(TO_DATE('2019-04-10 00:00:00'),'YYYY-MM-DD HH24:MI:SS') FROM DUAL;

update reservation set hotelCode='AAA';
select * from reservation;
delete from reservation where reserveCode>1000;