-- review_comment dummy data
CREATE TABLE REVIEW_COMMENT (
    REVIEWCMTCODE NUMBER(9) PRIMARY KEY, 
    GUESTID VARCHAR2(30) REFERENCES GUEST(GUESTID), 
    REVIEWCODE NUMBER(9) REFERENCES HOTEL_REVIEW(REVIEWCODE) ON DELETE CASCADE, 
    REVIEWCMTCONTENT VARCHAR2(1000) NOT NULL, 
    REVIEWCMTDATE DATE DEFAULT SYSDATE, 
    REVIEWCMTIP VARCHAR2(30) NOT NULL,
    REVIEWCMTGROUP NUMBER(9) NOT NULL,
    REVIEWCMTSTEP NUMBER(9) NOT NULL,
    REVIEWCMTINDENT NUMBER(9) NOT NULL
);
INSERT INTO REVIEW_COMMENT (REVIEW_COMMENT_SEQ.NEXTVAL, 'qqq', 12, '사진 보니 저도 기념일에 가고싶어요!', SYSDATE, '110.325.070.086', REVIEW_COMMENT_SEQ.CURRVAL, 0, 0);
INSERT INTO REVIEW_COMMENT (REVIEW_COMMENT_SEQ.NEXTVAL, 'www', 12, '객실은 넓은편인가요??', SYSDATE, '110.325.070.086', REVIEW_COMMENT_SEQ.CURRVAL, 0, 0);