--------------------------------------------------------------------------------------------------
-- Query about  HOTEL_REVIEW
--------------------------------------------------------------------------------------------------
SELECT * FROM HOTEL_REVIEW;
-- #. 리뷰 개수
SELECT COUNT(*) FROM HOTEL_REVIEW REVIEW, GUEST WHERE REVIEW.GUESTID=GUEST.GUESTID AND HOTELCODE='AAA';

-- #. 리뷰 목록(리뷰 모든 필드랑 게스트이름, 객실이름)
SELECT REVIEW.*, GUESTNAME, (SELECT ROOMNAME FROM ROOM WHERE ROOM.ROOMCODE=(SELECT ROOMCODE FROM RESERVATION WHERE RESERVATION.RESERVECODE=REVIEW.RESERVECODE)) AS ROOMNAME,
(SELECT COUNT(*) FROM REVIEW_COMMENT WHERE REVIEWCODE=REVIEW.REVIEWCODE) AS COMMENTCNT
FROM HOTEL_REVIEW REVIEW, GUEST WHERE REVIEW.GUESTID=GUEST.GUESTID AND HOTELCODE='AAA' ORDER BY REVIEWCODE DESC;

-- -- TOP-N
SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM (
SELECT REVIEW.*, GUESTNAME, (SELECT ROOMNAME FROM ROOM WHERE ROOM.ROOMCODE=(SELECT ROOMCODE FROM RESERVATION WHERE RESERVATION.RESERVECODE=REVIEW.RESERVECODE)) AS ROOMNAME 
FROM HOTEL_REVIEW REVIEW, GUEST WHERE REVIEW.GUESTID=GUEST.GUESTID AND HOTELCODE='AAA' ORDER BY REVIEWCODE DESC
) ALLIAS) WHERE RN BETWEEN 1 AND 4;

-- #. 리뷰 작성
INSERT INTO HOTEL_REVIEW (REVIEWCODE, GUESTID, RESERVECODE, HOTELCODE, REVIEWTITLE, REVIEWCONTENT, REVIEWFILE, REVIEWDATE, REVIEWIP, REVIEWSCORE) 
VALUES (HOTEL_REVIEW_SEQ.NEXTVAL, 'ggg', 7922, 'AAA', 'COZY CONE', 'IT IS REALLY COMFORTABLE', 'room.jpg', SYSDATE, '204.24.31.678', 4.5);

-- #. 호텔 총평점 업데이트(리뷰 작성, 수정, 삭제할 때 항상 실행될 것)
UPDATE HOTEL SET HOTELSCORE=(SELECT SUM(REVIEWSCORE)/COUNT(REVIEWSCORE) FROM HOTEL_REVIEW WHERE HOTELCODE='AAA') WHERE HOTELCODE='AAA';

-- #. 리뷰 하나 가져오기
SELECT REVIEW.*, GUESTNAME, (SELECT ROOMNAME FROM ROOM WHERE ROOM.ROOMCODE=(SELECT ROOMCODE FROM RESERVATION WHERE RESERVATION.RESERVECODE=REVIEW.RESERVECODE)) AS ROOMNAME,
(SELECT COUNT(*) FROM REVIEW_COMMENT WHERE REVIEWCODE=1) AS COMMENTCNT
FROM HOTEL_REVIEW REVIEW, GUEST WHERE REVIEW.GUESTID=GUEST.GUESTID AND REVIEWCODE=1;

-- #. 리뷰 수정
UPDATE HOTEL_REVIEW SET REVIEWTITLE='MOD TITLE', REVIEWCONTENT='MOD CONTENT', REVIEWFILE='modFile.jpg', REVIEWIP='201.17.354.54', REVIEWSCORE='4.0' WHERE REVIEWCODE=1;

-- #. 리뷰 삭제
DELETE HOTEL_REVIEW WHERE REVIEWCODE=0;

--------------------------------------------------------------------------------------------------
-- Query about  REVIEW_COMMENT
--------------------------------------------------------------------------------------------------

-- #. 댓글 총 개수
SELECT COUNT(*) FROM REVIEW_COMMENT WHERE REVIEWCODE=1;

-- #. 댓글 목록
SELECT CMT.*, GUESTNAME FROM REVIEW_COMMENT CMT, GUEST WHERE CMT.GUESTID=GUEST.GUESTID AND REVIEWCODE=1 ORDER BY REVIEWCMTGROUP DESC, REVIEWCMTSTEP ASC;

-- -- TOP-N
SELECT * FROM (SELECT ROWNUM AS RN, ALLIAS.* FROM (SELECT CMT.*, GUESTNAME FROM REVIEW_COMMENT CMT, GUEST WHERE CMT.GUESTID=GUEST.GUESTID AND REVIEWCODE=1 ORDER BY REVIEWCMTGROUP DESC, REVIEWCMTSTEP ASC) ALLIAS) WHERE RN BETWEEN 2 AND 4;

-- #. 원댓글 작성
INSERT INTO REVIEW_COMMENT (REVIEWCMTCODE, GUESTID, REVIEWCODE, REVIEWCMTCONTENT, REVIEWCMTDATE, REVIEWCMTIP, REVIEWCMTGROUP, REVIEWCMTSTEP, REVIEWCMTINDENT) 
VALUES (REVIEW_COMMENT_SEQ.NEXTVAL, 'ggg', 1, 'GOOD REVIEW', SYSDATE, '110.325.070.086', REVIEW_COMMENT_SEQ.CURRVAL, 0, 0);

-- #. 대댓글 작성
INSERT INTO REVIEW_COMMENT (REVIEWCMTCODE, GUESTID, REVIEWCODE, REVIEWCMTCONTENT, REVIEWCMTDATE, REVIEWCMTIP, REVIEWCMTGROUP, REVIEWCMTSTEP, REVIEWCMTINDENT) 
VALUES (REVIEW_COMMENT_SEQ.NEXTVAL, 'ggg', 1, 'YOU R WELCOME', SYSDATE, '217.002.04.053', 1, 2, 2);

-- #. 대댓글 작성 전 STEP A
UPDATE REVIEW_COMMENT SET REVIEWCMTSTEP=REVIEWCMTSTEP+1 WHERE REVIEWCMTGROUP=1 AND REVIEWCMTSTEP>0;

-- #. 댓글 하나 가져오기
SELECT CMT.*, GUESTNAME FROM REVIEW_COMMENT CMT, GUEST WHERE CMT.GUESTID=GUEST.GUESTID AND REVIEWCMTCODE=2;

-- #. 댓글 수정
UPDATE REVIEW_COMMENT SET REVIEWCMTCONTENT='MOD COMMENT', REVIEWCMTIP='110.168.10.151' WHERE REVIEWCMTCODE=2;

-- #. 댓글 삭제(원댓글)
DELETE FROM REVIEW_COMMENT WHERE REVIEWCMTCODE=90;

-- #. 댓글 삭제 (대댓글)
UPDATE REVIEW_COMMENT SET REVIEWCMTCONTENT='삭제된 댓글입니다' WHERE REVIEWCMTCODE=31;

-- #. 대댓글이 있나 확인(나보다 step이 하나 큰 댓글의 indent가 내 indent보다 크면 대댓글이 존재)
SELECT REVIEWCMTINDENT FROM REVIEW_COMMENT WHERE REVIEWCMTGROUP = (SELECT REVIEWCMTGROUP FROM REVIEW_COMMENT WHERE REVIEWCMTCODE=36) AND REVIEWCMTSTEP = (SELECT REVIEWCMTSTEP+1 FROM REVIEW_COMMENT WHERE REVIEWCMTCODE=36); 

SELECT * FROM REVIEW_COMMENT;